
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB_RPLPC12
 */
public class DataSiswa extends javax.swing.JFrame {
    Connection koneksi;
    String id = "";

    /**
     * Creates new form DataSiswa
     */
    public DataSiswa() {
        initComponents();
        koneksi();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        txtkelas = new javax.swing.JTextField();
        jurusan = new javax.swing.JComboBox<>();
        tambah = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampil = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("DATA SISWA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel4.setText("Kelas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel5.setText("Jurusan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 220, -1));

        buttonGroup1.add(laki);
        laki.setText("Laki-Laki");
        getContentPane().add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        buttonGroup1.add(perempuan);
        perempuan.setText("Perempuan");
        getContentPane().add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));
        getContentPane().add(txtkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 220, -1));

        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RPL", "TBSM", "TATA BOGA", "TL", "TATA BUSANA" }));
        getContentPane().add(jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 220, -1));

        tambah.setText("Simpan");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 80, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 80, -1));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 70, -1));

        tampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "Kelas", "Jurusan"
            }
        ));
        jScrollPane1.setViewportView(tampil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 580, 160));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\LAB_RPLPC12\\Downloads\\wallpaperflare.com_wallpaper (1).jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        if(id == "") {
            tambah();
        }else {
            update();
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        edit();
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JRadioButton laki;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tampil;
    private javax.swing.JTextField txtkelas;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

    private void  koneksi(){
    try {
        String server = "jdbc:mysql://localhost:3306/db_batagor";
        String user = "root";
        String pass = "";
        
        DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        koneksi = DriverManager.getConnection(server, user, pass);
   } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    
private void tampil(){
    DefaultTableModel data = (DefaultTableModel) tampil.getModel();
    data.setRowCount(0);
    
    try {
        String sql = "SELECT * FROM tb_siswa";
        ResultSet res = koneksi.createStatement().executeQuery(sql);
        while(res.next()){
                data.addRow(new Object[]{
                    res.getString(1), res.getString(2),
                    res.getString(3), res.getString(4),
                    res.getString(5) });
                    tampil.setModel(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}    

private void tambah(){
    try {
        String jk = (laki.isSelected()) ? "Laki-Laki" : "Perempuan";
        String sql = "INSERT INTO tb_siswa VALUES (null,"
                + "'" + txtnama.getText() + "'," 
                + "'" + jk + "',"
                + "'" + txtkelas.getText()+ "',"
                + "'" + jurusan.getSelectedItem().toString() + "')";
        
        int res = koneksi.createStatement().executeUpdate(sql);
        
        if (res > -1) {
            tampil();
            txtnama.setText("");
            laki.setSelected(false);
            perempuan.setSelected(false);
            txtkelas.setText("");
            jurusan.setSelectedIndex(0);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void hapus(){
     int row = tampil.getSelectedRow();
    String id = tampil.getValueAt(row, 0).toString();
    
    try {
        String sql = "DELETE FROM tb_siswa WHERE id="+id;
        int res = koneksi.createStatement().executeUpdate(sql);
        
        if (res > -1) {
            tampil();
            
        }
    } catch (Exception e) {
    }
    
}

private void edit(){
    int row = tampil.getSelectedRow();
    String id_siswa = tampil.getValueAt(row, 0).toString();
    
    try {
        String sql = "SELECT * FROM tb_siswa WHERE id="+id_siswa;
        ResultSet res = koneksi.createStatement().executeQuery(sql);
        
        while (res.next()) {
            id = res.getString(1);
            txtnama.setText(res.getString(2));
            if (res.getString(3) == "Laki-Laki") {
                laki.setSelected(true);
            }else {
                perempuan.setSelected(true);
            }
            txtkelas.setText(res.getString(4));
            jurusan.setSelectedItem(res.getString(5));
            edit.setEnabled(false);
            
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
   
}

private void clear(){
            id = null;
            txtnama.setText("");
            laki.setSelected(false);
            perempuan.setSelected(false);
            txtkelas.setText("");
            jurusan.setSelectedIndex(0);
            edit.setEnabled(true);
}

private void update(){
    try {
        String jk = (laki.isSelected()) ? "Laki-Laki" : "perempuan";
        String sql = "UPDATE tb_siswa SET "
                + "nama = '" + txtnama.getText() + "'," 
                + "jenis_kelamin = '" + jk + "',"
                + "kelas = '" + txtkelas.getText()+ "',"
                + "jurusan = '" + jurusan.getSelectedItem().toString() + "'  "
                + "WHERE id = " + id;
        
        int res = koneksi.createStatement().executeUpdate(sql);
        
        if (res > -1) {
            tampil();
            clear();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        
    }
}
    
}
