
import static java.lang.ref.Cleaner.create;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB_RPLPC12
 */
public class gudang extends javax.swing.JFrame {
    Connection Koneksi;
    /**
     * Creates new form gudang
     */
    public gudang() {
        initComponents();
        koneksi();
        tampil();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtnambar = new javax.swing.JTextField();
        qty = new javax.swing.JSpinner();
        jenisbr = new javax.swing.JComboBox<>();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("              DATA BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 500, 40));

        jLabel2.setText("kode                :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel3.setText("Nama Barang :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel4.setText("Jenis                 :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel5.setText("Qty                   :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));
        getContentPane().add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 164, -1));
        getContentPane().add(txtnambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 164, -1));
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 164, -1));

        jenisbr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bahan baku", "bahan produksi" }));
        getContentPane().add(jenisbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 164, -1));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 180, -1, -1));

        edit.setText("Edit");
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        clear.setText("Clear");
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode", "Nama Barang", "Jenis Barang", "Qty"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 470, 185));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
       create();
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisbr;
    private javax.swing.JSpinner qty;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnambar;
    // End of variables declaration//GEN-END:variables

private void  koneksi(){
    try {
        String server = "jdbc:mysql://localhost:3306/db_tahu";
        String user = "root";
        String pass = "";
        
        DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        Koneksi = DriverManager.getConnection(server, user, pass);
   } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void tampil(){
    DefaultTableModel data = (DefaultTableModel) tabel.getModel();
    data.setRowCount(0);
    
    try {
        String sql = "SELECT * FROM tb_barang";
        ResultSet res = Koneksi.createStatement().executeQuery(sql);
        while(res.next()){
                data.addRow(new Object[]{
                    res.getString(1), res.getString(2),
                    res.getString(3), res.getString(4),
                    res.getString(5)});
                    tabel.setModel(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void create(){
    try {
        String sql = "INSERT INTO tb_barang VALUES (null,"
                + "'" + txtkode.getText() + "',"
                + "'" + txtnambar.getText() + "',"
                + "'" + jenisbr.getSelectedItem().toString() + "',"
                + "'" + qty.getValue().toString() + "')";
        
        int res = Koneksi.createStatement().executeUpdate(sql);
        
        if (res > -1) {
            tampil();
            txtkode.setText("");
            txtnambar.setText("");
            jenisbr.setSelectedIndex(0);
            qty.setValue(0);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void delete(){
    int row = tabel.getSelectedRow();
    String id = tabel.getValueAt(row, 0).toString();
    
    try {
        String sql = "DELETE FROM tb_barang WHERE id="+id;
        int res = Koneksi.createStatement().executeUpdate(sql);
        
        if (res > -1) {
            tampil();
            
        }
    } catch (Exception e) {
    }
}



}
