
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB_RPLPC12
 */
public class Pinjaman extends javax.swing.JFrame {
    Connection koneksi;

    /**
     * Creates new form Pinjaman
     */
    public Pinjaman() {
        initComponents();
        koneksi();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        txttelepon = new javax.swing.JTextField();
        jenispin = new javax.swing.JComboBox<>();
        nominal = new javax.swing.JSpinner();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tampil = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("PENGAJUAN PINJAMAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 610, 70));

        jLabel2.setText("Nama             :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel3.setText("Alamat           :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel5.setText("Telepon             :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel6.setText("Jenis pinjaman :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel7.setText("Nominal            :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 340, -1));

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 340, 100));
        getContentPane().add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 340, -1));

        jenispin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kredit Perumahan", "Kredit Kendaraan", "Kredit Usaha" }));
        getContentPane().add(jenispin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 340, -1));
        getContentPane().add(nominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 340, -1));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 80, -1));

        edit.setText("Edit");
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 80, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 80, -1));

        clear.setText("Clear");
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 80, -1));

        tampil.setAutoCreateRowSorter(true);
        tampil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Alamat", "Telepon", "Jenis Pinjaman", "Nominal"
            }
        ));
        jScrollPane2.setViewportView(tampil);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 640, 170));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\LAB_RPLPC12\\Downloads\\lettuce.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -20, 130, 170));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\LAB_RPLPC12\\Downloads\\3240.png_300-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 250, 230));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\LAB_RPLPC12\\Downloads\\onion.png")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 220));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 500)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\LAB_RPLPC12\\Downloads\\wallpaperflare.com_wallpaper.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, -240, 1130, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenispin;
    private javax.swing.JSpinner nominal;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tampil;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables

private void  koneksi(){
    try {
        String server = "jdbc:mysql://localhost:3306/db_zaky_praukk";
        String user = "root";
        String pass = "";
        
        DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        koneksi = DriverManager.getConnection(server, user, pass);
   } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void tampil(){
    DefaultTableModel data = (DefaultTableModel) tampil.getModel();
    data.setRowCount(0);
    
    try {
        String sql = "SELECT * FROM tb_pinjaman";
        ResultSet res = koneksi.createStatement().executeQuery(sql);
        while(res.next()){
                data.addRow(new Object[]{
                    res.getString(1), res.getString(2),
                    res.getString(3), res.getString(4),
                    res.getString(5), res.getString(6)});
                    tampil.setModel(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void tambah(){
    try {
        String sql = "INSERT INTO tb_pinjaman VALUES (null,"
                + "'" + txtnama.getText() + "',"
                + "'" + txtalamat.getText() + "',"
                + "'" + txttelepon.getText() + "',"
                + "'" + jenispin.getSelectedItem().toString() + "',"
                + "'" + nominal.getValue().toString() + "')";
        
        int res = koneksi.createStatement().executeUpdate(sql);
        
        if (res > -1) {
            tampil();
            txtnama.setText("");
            txtalamat.setText("");
            txttelepon.setText("");
            jenispin.setSelectedIndex(0);
            nominal.setValue(0);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void hapus(){
     int row = tampil.getSelectedRow();
    String id = tampil.getValueAt(row, 0).toString();
    
    try {
        String sql = "DELETE FROM tb_pinjaman WHERE id="+id;
        int res = koneksi.createStatement().executeUpdate(sql);
        
        if (res > -1) {
            tampil();
            
        }
    } catch (Exception e) {
    }
    
}
    

}
